export const ERROR_CODE = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    AUTH_ALREADY_SETUP: 'AUTH_ALREADY_SETUP',
    AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
    AUTH_LOCKED: 'AUTH_LOCKED',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
    ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
    ATTACHMENT_FILE_NOT_FOUND: 'ATTACHMENT_FILE_NOT_FOUND',
    ATTACHMENT_PATH_INVALID: 'ATTACHMENT_PATH_INVALID',
    SYNC_SOURCE_UNAVAILABLE: 'SYNC_SOURCE_UNAVAILABLE',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]
